name: nexo_flutter
description: A new Flutter project with Serverpod.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  app_settings: ^4.2.0
  cached_network_image: ^3.2.3
  file_picker: ^5.2.7
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_riverpod: ^2.3.0
  flutter_sensors: ^1.0.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  go_router: ^6.2.0
  image: ^3.2.2
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+1
  intl: any
  json_annotation: ^4.8.0
  latlong2: ^0.8.1
  mockito: ^5.3.2
  nexo_client:
    path: ../nexo_client
  permission_handler: ^10.2.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  rxdart: ^0.27.7
  sensors_plus: ^2.0.2
  serverpod_auth_email_flutter: ^1.0.1
  serverpod_auth_shared_flutter: ^1.0.1
  serverpod_flutter: ^1.0.1
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  generate: true
